name: update benchmarks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: 11 0 * * *

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Benchmark
        run: pnpm benchmark

      - name: update readme
        run: pnpm update-readme

      - name: Commit and push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add ./README.md
          git add ./benchmark-results.json
          git commit -m "chore: update benchmarks"
          git push
