name: update benchmarks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ./bench/*.ts
      - ./scripts/update-readme.ts
      - ./.github/workflows/benchmark.yaml
      - ./package.json
      - ./pnpm-lock.yaml
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - ./bench/*.ts
      - ./scripts/update-readme.ts
      - ./.github/workflows/benchmark.yaml
      - ./package.json
      - ./pnpm-lock.yaml
  schedule:
    - cron: 11 0 * * *

jobs:
  build:
    if: github.repository_owner == 'luxass'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Benchmark
        run: pnpm benchmark

      - name: update readme
        run: pnpm update-readme

      - name: readme contents
        id: readme
        run: |
          BENCH_RESULTS=$(cat README.md | sed -n '/<!-- bench:start -->/,/<!-- bench:end -->/{/<!-- bench:start -->/d; /<!-- bench:end -->/d; p;}')
          echo "BENCH_RESULTS=$BENCH_RESULTS" >> $GITHUB_OUTPUT

      - name: create pr
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          commit-message: "chore: update benchmarks"
          title: "chore: update benchmarks"
          body: |
            This PR updates the benchmarks.

            ## Overview
            ${{ steps.readme.outputs.BENCH_RESULTS }}
          branch: update-benchmarks
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: luxass
